### ISSUE TITLE
eoc test fails on unit tests

### ISSUE THREAD

**Issue by deemp** [objectionary/eo#2868]
eoc version: 0.34.1

I run `eoc test` in the `eo-runtime/src/test/eo/org/eolang` directory.
on tests from https://github.com/objectionary/eo/tree/master/eo-runtime/src/test/eo/org/eolang and get the following error:

```
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
[ERROR] Failed to parse '/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo:254': [254:6] no viable alternative at input 'seq > @\n    INT*\n      INT# A.': "      # A."
[ERROR] Failed to parse '/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo:254': [254:-1] extraneous input 'INT' expecting {COMMENT, 'Q', 'QQ', '*', '<', '&', '$', '[', '(', '@', '^', BYTES, BOOL, STRING, INT, FLOAT, HEX, NAME, TEXT, UNTAB}: "      # A."
[ERROR] Failed to parse '/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo:255': [255:-1] extraneous input 'INT' expecting {COMMENT, 'Q', 'QQ', '*', '<', '&', '$', '[', '(', '@', '^', BYTES, BOOL, STRING, INT, FLOAT, HEX, NAME, TEXT, UNTAB}: "      [] > a"
[ERROR] Failed to parse '/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo:259': [259:-1] mismatched input 'EXPONENT' expecting {<EOF>, COMMENT, 'Q', 'QQ', '*', '<', '&', '$', '[', '(', '@', '^', BYTES, BOOL, STRING, INT, FLOAT, HEX, NAME, TEXT}: "[] > calling-caged-function"
[ERROR] net.sf.saxon.style.XSLMessage@69316092: This transformation must be applied only after you remove @method attributes from objects, using 'wrap-method-calls.xsl'
[ERROR] #fatalError(): Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[ERROR] 'org.eolang.maven.ShakeMojo@395a30a' execution failed
[ERROR] Processing terminated by xsl:message at line 82 in set-locators.xsl
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.34.1:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@43c87306' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.ShakeMojo@395a30a' execution failed: java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.jaxp.TransformerImpl: ; Processing terminated by xsl:message at line 82 in set-locators.xsl; SystemID: file:///org/eolang/parser/set-locators.xsl; Line#: 82; Column#: 36 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/nix/store/qd4rdsq1iykfjiyq8dijcn93zb38y0sf-unknown/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.34.1 -Deo.hash=0.34.1 --quiet -Deo.sourcesDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang -Deo.targetDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc -Deo.outputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/classes -Deo.generatedDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/generated-sources -Deo.placed=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

I removed `runtime-tests.eo` and got this error:

```
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
[ERROR] Failed while trying to save to /home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/4-pull/org/eolang/io/tupled-stdout.eo
[ERROR] EO object 'org.eolang.io.tupled-stdout' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package.
[ERROR] 'org.eolang.maven.PullMojo@14852fbd' execution failed
[ERROR] Failed while trying to save to /home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/4-pull/org/eolang/io/tupled-stdout.eo
[ERROR] EO object 'org.eolang.io.tupled-stdout' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package.
[ERROR] Failed to execute goal org.eolang:eo-maven-plugin:0.34.1:assemble (default-cli) on project eoc: 'org.eolang.maven.AssembleMojo@43c87306' execution failed: java.lang.IllegalStateException: org.apache.maven.plugin.MojoFailureException: 'org.eolang.maven.PullMojo@14852fbd' execution failed: java.io.IOException: Failed while trying to save to /home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/4-pull/org/eolang/io/tupled-stdout.eo: EO object 'org.eolang.io.tupled-stdout' is not found in this GitHub repository: https://github.com/objectionary/home. This means that you either misspelled the name of it or simply referred to your own local object somewhere in your code as if it was an object of 'org.eolang' package. Check the sources and make sure you always use +alias meta when you refer to an object outside of 'org.eolang', even if this object belongs to your package. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/nix/store/qd4rdsq1iykfjiyq8dijcn93zb38y0sf-unknown/lib/node_modules/eolang/mvnw/mvnw eo:assemble -Deo.version=0.34.1 -Deo.hash=0.34.1 --quiet -Deo.sourcesDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang -Deo.targetDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc -Deo.outputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/classes -Deo.generatedDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/generated-sources -Deo.placed=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

**Comment by yegor256** [comment]
@deemp the version of `eoc` you are using is too old -- it doesn't understand the recent syntax of EO, I believe. Try to use EO tests of version 0.34.1. @maxonfjvipon am I right?

**Comment by deemp** [comment]
Switched to [0.34.1](https://github.com/objectionary/eo/tree/0.34.1). Here's the error

```
EO objects registered in .eoc/eo-foreign.json
Assembling into .eoc
EO program assembled in .eoc
EO program verified in .eoc
Java sources generated in .eoc/generated-sources
[ERROR] COMPILATION ERROR : files generated so far...
[ERROR] /home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/generated-sources/EOorg/EOeolang/EOnon_empty_tuple_length_testTest.java:[150,14] error while writing EOorg.EOeolang.EOnon_empty_tuple_length_testTest.EOω1arr: bad filename RelativeFile[EOorg/EOeolang/EOnon_empty_tuple_length_testTest$EOω1arr.class]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-cli) on project eoc: Compilation failure
[ERROR] /home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/generated-sources/EOorg/EOeolang/EOnon_empty_tuple_length_testTest.java:[150,14] error while writing EOorg.EOeolang.EOnon_empty_tuple_length_testTest.EOω1arr: bad filename RelativeFile[EOorg/EOeolang/EOnon_empty_tuple_length_testTest$EOω1arr.class]
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
The command "/nix/store/qd4rdsq1iykfjiyq8dijcn93zb38y0sf-unknown/lib/node_modules/eolang/mvnw/mvnw compiler:compile -Deo.version=0.34.1 -Deo.hash=0.34.1 --quiet -Deo.sourcesDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang -Deo.targetDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc -Deo.outputDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/classes -Deo.generatedDir=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/generated-sources -Deo.placed=/home/eyjafjallajokull/Desktop/gh/normalizer/eo/eo-runtime/src/test/eo/org/eolang/.eoc/eo-placed.csv -Deo.placedFormat=csv --batch-mode --color=never --update-snapshots --fail-fast --strict-checksums" exited with #1 code
```

**Comment by maxonfjvipon** [comment]
@deemp what version of `eoc` do you use? The last one is [0.15.1](https://github.com/objectionary/eoc/tree/0.15.1)

**Comment by maxonfjvipon** [comment]
@deemp the last version of `eoc` (which is 0.15.1) uses `eo` of version `0.34.1`. So if you do:
1. clear all cache
2. run `eoc test` for [`runtime-tests.eo`](https://github.com/objectionary/eo/blob/0.34.1/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo) of version `0.34.1`

it should work just fine

**Comment by deemp** [comment]
Ok, installed `eolang` it via `npm`, and it worked.
