### PR TITLE
Cover deleting a directory whose subdirectory is not empty

### PR DESCRIPTION
**Pull request by yegor256**
This branch started as a fix for the `ec2` failure on `master` ([run 32966035691](https://github.com/objectionary/eo/actions/runs/32966035691/job/98169172783)):

```
[ERROR] EOdirectoryTest.can_delete_an_empty_directory:3642 expected: <true> but was: <false>
```

While it was open, #7735 landed the same fix on `master` (`d.as-path.as-file.deleted` plus the `bool.not d` correction in `can-delete-an-already-absent-directory`), so the failure is already gone. The branch is rebuilt on top of that and now carries only what `master` still lacks: a test for the one property of `directory.deleted` that nothing asserts.

## Why

`directory.deleted` walks the tree, deletes each entry the walk offers and then removes the root. The walk hands out a child before its parent, so the recursion deletes the head of the tuple before it steps into the tail. Reverse those two lines and `rmdir` is asked to remove a directory that still holds entries.

Neither existing test notices:

- `can-delete-a-directory-with-a-file-and-a-directory` puts an **empty** directory next to a file, and an empty directory is removable in any order;
- `can-delete-a-directory-with-files-recursively` keeps its two files flat.

## What changed

One test in `eo-runtime/src/main/eo/directory/deleted.eo`, hanging a file inside a subdirectory — the shape that needs the child gone first.

## Verification

On this branch:

```
mvn -pl eo-runtime test -Deo.deadline=600 -Dtest='EOdirectoryTest#can_delete_a_directory_with_a_nested_file'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

With the recursion in `deleted.eo` stepping into `tup.tail` before deleting `tup.head` (the deliberate break, not part of this diff), the same test fails:

```
[ERROR] EOdirectoryTest.can_delete_a_directory_with_a_nested_file » ExFailure ...
  Cant delete the file '/tmp/.../...': Directory not empty
```

`format` and the lints run clean over the edited source (`All 171 EO source(s) are formatted canonically`).

Aside, from chasing the original failure: with `eo.deadline` at one second, `Deadline` turns a timeout into a `TestAbortedException`, so surefire reports slow tests as skipped — 31 of the 44 tests in `EOdirectoryTest` in that EC2 run. Three of this object's four tests were failing on `master` and only the fastest one was ever reported.

### CODE REVIEW

**Comment by yegor256** [comment]
`fast` is red on this head, and the failure is not this PR's.

**What fails.** Step 8 of the job, `mvn clean test -ntp -pl :eo-runtime '-Deo.deadline=3600' -Dtest=EOdirectoryTest` ([job](https://github.com/objectionary/eo/actions/runs/32979663225/job/98212909083)). The surefire fork dies after 19 minutes:

```
[ERROR] There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: Could not initialize class org.junit.platform.commons.util.ExceptionUtils
```

That `NoClassDefFoundError` is the aftermath of an `OutOfMemoryError`: the class whose static initializer ran out of heap cannot be initialized again. No test failed — the JVM died before surefire could report anything.

**Why it is not this PR's.** I checked out `master`'s own `eo-runtime/src/main/eo/directory/deleted.eo` over this branch's copy, so the tree had none of my change, and ran the same command locally:

```
[INFO] Running org.eolang.EOdirectoryTest
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "JNA Cleaner"
```

The same step failed the same way on #7735 ([job](https://github.com/objectionary/eo/actions/runs/32967685890/job/98173825531)), which is merged into `master`.

**Nothing is hiding behind the crash.** With the heap raised the whole class is green:

```
mvn surefire:test -pl eo-runtime -Deo.deadline=3600 -Dheap-size=12G -Dtest=EOdirectoryTest
[INFO] Tests run: 44, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 164.2 s
```

Every walk test also passes on its own at the default 8G (`can_walk_recursively` 25s, `can_walk_recursively_across_nested_directories` 15s, `can_walk_past_a_symbolic_link_to_its_own_parent` 5s). The exhaustion comes from the class running as a whole: `eo.deadline` at 3600 lets the tests that the one-second deadline normally aborts run to completion, four at a time under the `configurationParameters` in `eo-runtime/pom.xml`, and their combined live set does not fit in `-Xmx8G`.

**Suggested direction**, not pushed here since it touches neither this diff nor `directory.deleted`:

- give that one step a bigger heap, e.g. `-Dheap-size=12G` on the `fast` step — 12G was enough locally, though a 16 GB runner also hosts the Maven JVM, so it wants a trial;
- or shrink the per-JVM working set for the no-deadline run (fewer tests per fork, or a lower parallelism). Note that `-Djunit.jupiter.execution.parallel.*` on the command line will not do it: surefire passes the pom's `configurationParameters` as launcher parameters, which outrank system properties, so the change has to happen in `eo-runtime/pom.xml` or in the workflow step itself.

I have not re-run the job: the OOM reproduces deterministically here, twice, including on `master`'s own source, so a second 26-minute run would only spend CI to show the same thing. Happy to open a separate PR for whichever of the two directions you prefer.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by 0crat** [comment]
@yegor256 Thanks for the contribution! You've earned +4 points for this: +16 as a basis; -8 for the lack of code review; -4 for too few (8) hits-of-code. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running score is [+1807](https://www.eolang.org/zerocracy/objectionary-vitals.html); don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too).
